apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: threatstack-agent
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: threatstack-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: threatstack-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: threatstack-agent
subjects:
- kind: ServiceAccount
  name: threatstack-agent
  namespace: default
          name: hostfs
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: threatstack-agent
spec:
  selector:
    matchLabels:
      name: "threatstack-agent"
  template:
    metadata:
      labels:
        name: "threatstack-agent"
      name: threatstack-agent
    spec:
      # This toleration schedules the threatstack-agent on all nodes.
      # An empty key with operator Exists matches all keys, values and effects
      # which means this will tolerate everything.
      tolerations:
      - operator: Exists
      hostNetwork: true
      hostPID: true
      containers:
      - image: threatstack/ts-docker2:2.1.0
        imagePullPolicy: Always
        name: threatstack-agent
        env:
          - name: THREATSTACK_SETUP_ARGS
            value: "-deploy-key <REPLACE_WITH_VALID_DEPLOY_KEY> -ruleset 'Base Rule Set, Docker Rule Set, Kubernetes Rule Set'"
          - name: THREATSTACK_CONFIG_ARGS
            value: "enable_kubes 1 enable_containers 1 log.level info"
        securityContext:
          privileged: false
          capabilities:
            add: ["AUDIT_CONTROL", "AUDIT_READ", "SYS_CHROOT", "CHOWN","DAC_OVERRIDE", "DAC_READ_SEARCH", "FOWNER", "FSETID", "SETGID", "SETUID", "SYS_ADMIN", "SYS_PTRACE"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: hostfs
            mountPath: /threatstackfs
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /
          name: hostfs
